// shadow-compare.ts: the phase 4 observation run. Compares the incumbent submitter against a
// candidate over synthetic proofs only, and prints whether a cutover may proceed.
//
//   npx tsx apps/api/scripts/shadow-compare.ts [candidate] [count]
//
// It sends nothing real: the payloads are generated by cutover.ts and refused if not provably
// synthetic. With no credentials both adapters simply degrade, which is still a valid run — it
// proves the pair agrees. Nothing here writes to the store.

import { compareSubmitters, cutoverReady, syntheticPayload, type ComparisonRow } from "../src/cutover.js";
import { localKeySubmitter } from "../src/submitters/local-key.js";
import { noneSubmitter } from "../src/submitters/none.js";
import { ozRelayerSubmitter } from "../src/submitters/openzeppelin-relayer.js";
import type { AttestationSubmitter } from "../src/submitter.js";

const ADAPTERS: Record<string, AttestationSubmitter> = {
  "local-key": localKeySubmitter,
  "openzeppelin-relayer": ozRelayerSubmitter,
  none: noneSubmitter,
};

async function main(): Promise<void> {
  const candidateName = process.argv[2] ?? "none";
  const count = Number(process.argv[3] ?? 5);

  const candidate = ADAPTERS[candidateName];
  if (!candidate) {
    console.error(`unknown candidate "${candidateName}". known: ${Object.keys(ADAPTERS).join(", ")}`);
    process.exit(2);
  }

  const rows: ComparisonRow[] = [];
  for (let i = 0; i < count; i++) {
    rows.push(await compareSubmitters(localKeySubmitter, candidate, syntheticPayload(i)));
  }

  for (const r of rows) {
    console.log(
      `${r.incumbent} vs ${r.candidate}: ${r.outcome}` +
        ` | agrees=${r.agrees} | calldata-deterministic=${r.calldataDeterministic}`,
    );
  }

  const ready = cutoverReady(rows);
  console.log(`\ncutover ${ready ? "READY" : "HELD"} over ${rows.length} synthetic proofs`);
  console.log(
    ready
      ? "Keep the incumbent configured for one observation window before removing it."
      : "A divergence holds the switch. Do not cut over.",
  );
  process.exit(ready ? 0 : 1);
}

void main();
